from dialogue_manager import *

if __name__ == "__main__":
    dialogue_manager = DialogueManager(RESOURCE_PATH)
    response = dialogue_manager.generate_answer("age in c#")
    print(response)
    print("---------------------response-------------------------")
    response = dialogue_manager.generate_answer("how are you")
    print(response)
    print("---------------------response-------------------------")
    response = dialogue_manager.generate_answer("how old are you?")
    print(response)
    print("---------------------response-------------------------")
    response = dialogue_manager.generate_answer("What is intelligence?")
    print(response)
    print("---------------------response-------------------------")
    response = dialogue_manager.generate_answer("Ultimate Question of Life, the Universe, and Everything?")
    print(response)
    print("---------------------response-------------------------")
    response = dialogue_manager.generate_answer("quick sort for array ")
    print(response)
    print("---------------------response-------------------------")
    response = dialogue_manager.generate_answer("run cpp code in python")
    print(response)
    print("---------------------response-------------------------")
    response = dialogue_manager.generate_answer("dynamically delete div")
    print(response)
    print("---------------------response-------------------------")
